apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform
  namespace: devops-platform
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-platform
  template:
    metadata:
      labels:
        app: devops-platform
    spec:
      containers:
        - name: devops-platform
          image: agarciafer/devops-platform:v7
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "dev"  
          
